### ISSUE TITLE
contentView: It might be confusing to create a view if it doesn't exist

### ISSUE THREAD

**Issue by MaherKSantina** [BalazsSzamody/FFConfigurableView#2]
I just noticed in this function:
```
func contentView<T>(_ type: T.Type) -> T where T: UIView {
        if let view = subviews.first as? T {
            return view
        } else {
            subviews
                .forEach({ $0.removeFromSuperview() })
            let view = T.fromNib()
            addSubviewWithConstraints(view)
            setNeedsLayout()
            layoutIfNeeded()
            return view
        }
    }
```
I feel like it might be a bit confusing to add the view every time we try to access it right? The function name wouldn't indicate that you're creating one if it doesn't exist

**Comment by BalazsSzamody** [comment]
I am not sure about this. From the user's point-of-view the main point is that the view is there (and it won't create a new one if it's already there) And as the `configureContentView` calls this it is always after the first configuration.

**Comment by MaherKSantina** [comment]
Ohh okayy sounds good, thanks for the clarification! 👍
