### ISSUE TITLE
Can't reference views from outside the main bundle

### ISSUE THREAD

**Issue by MaherKSantina** [BalazsSzamody/FFConfigurableView#3]
I noticed this function code:
```
static func fromNib(_ nibName: String? = nil, positionInNib position: Int = 0) -> Self {
        guard let view = UINib(nibName: nibName ?? String(describing: Self.self), bundle: nil)
                .instantiate(withOwner: nil, options: nil)[position] as? Self else {
            preconditionFailure("Nib object instantiaton or cast failed, check the '.xib' file")
        }
        
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }
```
I think instead of setting `bundle: nil` you set `bundle: Bundle.main` might solve the issue of referencing the xibs in the test target (Not 100% sure). Or you can add the Bundle as an argument to the function and default it similar to the other arguments

**Comment by BalazsSzamody** [comment]
@MaherKSantina Thanks. I fixed it. The Package still can't pick up the nib, but it works in a parent project. Plus I included the parameter too. Included in `0.0.4`
